default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: <%= ENV.fetch("DB_USER") { 'postgres' } %>
  password: <%= ENV.fetch("DB_PASSWORD") {} %>

development:
  <<: *default
  database: auth_session_development

test:
  <<: *default
  database: auth_session_test

# Doc: https://devcenter.heroku.com/articles/ruby-support#build-behavior
# Doc: https://guides.rubyonrails.org/configuring.html#configuring-a-database
# HerokuのPostgresアドオンを使用
production:
  url: <%= ENV["DATABASE_URL"] %>
